export const courses = [
  {
    id: 1,
    title: "Learn JavaScript",
    description: "Basics of JS",
    level: "Beginner",
    price: 0,
    categorySlug: "web-development",
    duration: 4,
    image: "https://source.unsplash.com/400x200/?javascript,code",
  },
  {
    id: 2,
    title: "React Native Basics",
    description: "Build mobile apps",
    level: "Beginner",
    price: 0,
    categorySlug: "mobile-app-development",
    duration: 6,
    image: "https://source.unsplash.com/400x200/?react,code",
  },
  {
    id: 3,
    title: "Machine Learning 101",
    description: "Intro to ML",
    level: "Intermediate",
    price: 50,
    categorySlug: "ai-ml",
    duration: 15,
    image: "https://source.unsplash.com/400x200/?machinelearning,ai",
  },
  {
    id: 4,
    title: "Machine Learning 101",
    description: "Intro to ML",
    level: "Intermediate",
    price: 50,
    categorySlug: "ai-ml",
    duration: 15,
    image: "https://source.unsplash.com/400x200/?machinelearning,ai",
  },
];
