// export const courses = [
//   {
//     id: 1,
//     title: "Learn JavaScript",
//     slug: "learn-javascript",
//     description: "JavaScript is the most popular programming language for web development. In this course, you will learn the basics of JS including variables, functions, loops, arrays, objects, DOM manipulation, and events. By the end, you'll be able to create dynamic web pages and interactive UI elements. This course also introduces modern ES6+ features, asynchronous programming with promises and async/await, and working with APIs. Ideal for beginners who want a strong foundation in JavaScript.",
//     category: "Web Development",
//     categorySlug: "web-development",
//     level: "Beginner",
//     price: 0,
//     duration: "4 months",
//     instructor: "Muhammad Ali",
//     rating: 4.5,
//     popularity: 95,
//     createdAt: "2026-01-01",
//     image: "https://i.imgur.com/8Km9tLL.jpg",
//   },
//   {
//     id: 2,
//     title: "React Native Basics",
//     slug: "react-native-basics",
//     description: "React Native allows you to build cross-platform mobile apps using JavaScript and React. This course covers all the fundamentals, including components, props, state, hooks, navigation, styling, and integrating APIs. You will create several small projects and a final app to practice everything you've learned. By the end, you'll be able to publish simple mobile apps for both iOS and Android platforms.",
//     category: "Mobile App Development",
//     categorySlug: "mobile-app-development",
//     level: "Beginner",
//     price: 0,
//     duration: "12 months",
//     instructor: "Muhammad Ali",
//     rating: 4.2,
//     popularity: 85,
//     createdAt: "2026-01-15",
//     image: "https://i.imgur.com/2yaf2wb.jpg",
//   },
//   {
//     id: 3,
//     title: "Machine Learning 101",
//     slug: "machine-learning-101",
//     description: "Machine Learning is a subset of AI that allows systems to learn from data. This course will introduce you to supervised and unsupervised learning, regression, classification, clustering, decision trees, random forests, and neural networks. You will also learn to work with Python libraries like scikit-learn, pandas, and numpy. Practical examples and exercises are included to help you understand real-world applications such as predicting trends and building intelligent systems.",
//     category: "AI / ML",
//     categorySlug: "ai-ml",
//     level: "Intermediate",
//     price: 50,
//     duration: "15 weeks",
//     instructor: "Muhammad Ali",
//     rating: 4.8,
//     popularity: 90,
//     createdAt: "2026-02-01",
//     image: "https://i.imgur.com/3tL4U2j.jpg",
//   },
//   {
//     id: 4,
//     title: "Python for Data Science",
//     slug: "python-for-data-science",
//     description: "Python is the leading language for data analysis and data science. This course covers Python programming fundamentals, data structures, libraries like pandas, numpy, matplotlib, and seaborn, and performing data cleaning, analysis, and visualization. You will also learn about machine learning basics and how to build simple predictive models. By the end, you'll be comfortable analyzing datasets and generating insights using Python.",
//     category: "Data Science",
//     categorySlug: "data-science",
//     level: "Beginner",
//     price: 30,
//     duration: "3 months",
//     instructor: "Muhammad Ali",
//     rating: 4.6,
//     popularity: 80,
//     createdAt: "2026-02-05",
//     image: "https://i.imgur.com/7rD9r4K.jpg",
//   },
// ];

export const courses = [
  {
    id: 1,
    title: "Learn JavaScript",
    slug: "learn-javascript",
    description: "JavaScript is the most popular programming language for web development. Learn variables, loops, functions, objects, DOM, events, ES6+, async programming, and working with APIs.",
    category: "Web Development",
    categorySlug: "web-development",
    level: "Beginner",
    price: 0,
    duration: "4 months",
    instructor: "Muhammad Ali",
    rating: 4.5,
    popularity: 95,
    createdAt: "2026-01-01",
    image: "https://i.imgur.com/8Km9tLL.jpg",
  },
  {
    id: 2,
    title: "React Native Basics",
    slug: "react-native-basics",
    description: "Build cross-platform mobile apps using React Native. Covers components, hooks, navigation, styling, and integrating APIs with hands-on projects.",
    category: "Mobile App Development",
    categorySlug: "mobile-app-development",
    level: "Beginner",
    price: 0,
    duration: "12 months",
    instructor: "Muhammad Ali",
    rating: 4.2,
    popularity: 85,
    createdAt: "2026-01-15",
    image: "https://i.imgur.com/2yaf2wb.jpg",
  },
  {
    id: 3,
    title: "Machine Learning 101",
    slug: "machine-learning-101",
    description: "Introduction to Machine Learning: regression, classification, clustering, neural networks, Python libraries (numpy, pandas, scikit-learn) and real-world applications.",
    category: "AI / ML",
    categorySlug: "ai-ml",
    level: "Intermediate",
    price: 50,
    duration: "15 weeks",
    instructor: "Muhammad Ali",
    rating: 4.8,
    popularity: 90,
    createdAt: "2026-02-01",
    image: "https://i.imgur.com/3tL4U2j.jpg",
  },
  {
    id: 4,
    title: "Python for Data Science",
    slug: "python-for-data-science",
    description: "Learn Python programming, data analysis with pandas and numpy, data visualization with matplotlib and seaborn, and basics of machine learning.",
    category: "Data Science",
    categorySlug: "data-science",
    level: "Beginner",
    price: 30,
    duration: "3 months",
    instructor: "Muhammad Ali",
    rating: 4.6,
    popularity: 80,
    createdAt: "2026-02-05",
    image: "https://i.imgur.com/7rD9r4K.jpg",
  },
  {
    id: 5,
    title: "Advanced JavaScript",
    slug: "advanced-javascript",
    description: "Deep dive into advanced JS concepts: closures, prototypes, async/await, modules, event loop, and ES6+ features to write professional code.",
    category: "Web Development",
    categorySlug: "web-development",
    level: "Advanced",
    price: 70,
    duration: "5 months",
    instructor: "Ali Khan",
    rating: 4.7,
    popularity: 88,
    createdAt: "2026-01-20",
    image: "https://i.imgur.com/T5YxP7A.jpg",
  },
  {
    id: 6,
    title: "React JS Complete Guide",
    slug: "react-js-complete",
    description: "Learn React from scratch: components, hooks, context API, routing, state management, performance optimization, and deploying real-world applications.",
    category: "Web Development",
    categorySlug: "web-development",
    level: "Intermediate",
    price: 60,
    duration: "6 months",
    instructor: "Sara Ali",
    rating: 4.9,
    popularity: 92,
    createdAt: "2026-02-10",
    image: "https://i.imgur.com/LT3mLxg.jpg",
  },
  {
    id: 7,
    title: "Node.js & Express",
    slug: "nodejs-express",
    description: "Backend development with Node.js and Express: building APIs, connecting databases, authentication, middleware, and deployment techniques.",
    category: "Web Development",
    categorySlug: "web-development",
    level: "Intermediate",
    price: 55,
    duration: "5 months",
    instructor: "Ali Khan",
    rating: 4.5,
    popularity: 80,
    createdAt: "2026-02-15",
    image: "https://i.imgur.com/K6qaYtS.jpg",
  },
  {
    id: 8,
    title: "Full Stack Development",
    slug: "full-stack-development",
    description: "Become a full stack developer with React, Node.js, Express, MongoDB. Build complete web applications from frontend to backend.",
    category: "Web Development",
    categorySlug: "web-development",
    level: "Advanced",
    price: 100,
    duration: "8 months",
    instructor: "Sara Ali",
    rating: 4.8,
    popularity: 93,
    createdAt: "2026-02-18",
    image: "https://i.imgur.com/xTz6oHf.jpg",
  },
  {
    id: 9,
    title: "UI/UX Design Fundamentals",
    slug: "ui-ux-design",
    description: "Learn UI/UX design principles, Figma, Adobe XD, prototyping, and creating user-friendly interfaces.",
    category: "Design",
    categorySlug: "design",
    level: "Beginner",
    price: 0,
    duration: "3 months",
    instructor: "Hina Ali",
    rating: 4.4,
    popularity: 75,
    createdAt: "2026-01-05",
    image: "https://i.imgur.com/jT0Gg5f.jpg",
  },
  {
    id: 10,
    title: "Digital Marketing Basics",
    slug: "digital-marketing-basics",
    description: "Learn SEO, social media marketing, email marketing, PPC, content marketing, and analytics for online business growth.",
    category: "Marketing",
    categorySlug: "marketing",
    level: "Beginner",
    price: 20,
    duration: "2 months",
    instructor: "Ali Raza",
    rating: 4.3,
    popularity: 70,
    createdAt: "2026-01-12",
    image: "https://i.imgur.com/X2kZ5d7.jpg",
  },
  {
    id: 11,
    title: "Advanced React Native",
    slug: "advanced-react-native",
    description: "Master React Native: animations, navigation, state management, performance optimization, testing, and publishing apps.",
    category: "Mobile App Development",
    categorySlug: "mobile-app-development",
    level: "Advanced",
    price: 70,
    duration: "10 months",
    instructor: "Sara Ali",
    rating: 4.7,
    popularity: 85,
    createdAt: "2026-02-01",
    image: "https://i.imgur.com/6bQ6s3c.jpg",
  },
  {
    id: 12,
    title: "Data Science with R",
    slug: "data-science-r",
    description: "Learn R programming, data cleaning, visualization, statistics, and predictive modeling for data science projects.",
    category: "Data Science",
    categorySlug: "data-science",
    level: "Intermediate",
    price: 50,
    duration: "4 months",
    instructor: "Hina Ali",
    rating: 4.6,
    popularity: 80,
    createdAt: "2026-02-05",
    image: "https://i.imgur.com/FGy7b2g.jpg",
  },
  {
    id: 13,
    title: "AI & Deep Learning",
    slug: "ai-deep-learning",
    description: "Explore AI and deep learning: neural networks, CNNs, RNNs, TensorFlow, Keras, and building intelligent models.",
    category: "AI / ML",
    categorySlug: "ai-ml",
    level: "Advanced",
    price: 80,
    duration: "6 months",
    instructor: "Ali Raza",
    rating: 4.9,
    popularity: 90,
    createdAt: "2026-02-08",
    image: "https://i.imgur.com/MV5r3gS.jpg",
  },
  {
    id: 14,
    title: "SQL & Databases",
    slug: "sql-databases",
    description: "Learn SQL, relational databases, CRUD operations, joins, indexing, normalization, and working with MySQL and PostgreSQL.",
    category: "Web Development",
    categorySlug: "web-development",
    level: "Beginner",
    price: 30,
    duration: "3 months",
    instructor: "Ali Khan",
    rating: 4.5,
    popularity: 78,
    createdAt: "2026-01-18",
    image: "https://i.imgur.com/P9y6n0K.jpg",
  },
  {
    id: 15,
    title: "Cloud Computing Basics",
    slug: "cloud-computing-basics",
    description: "Learn cloud fundamentals: AWS, Azure, cloud storage, networking, virtualization, and deploying applications to the cloud.",
    category: "Cloud",
    categorySlug: "cloud",
    level: "Beginner",
    price: 40,
    duration: "2 months",
    instructor: "Sara Ali",
    rating: 4.4,
    popularity: 72,
    createdAt: "2026-01-22",
    image: "https://i.imgur.com/9hT7gkT.jpg",
  },
  {
    id: 16,
    title: "Kubernetes & Docker",
    slug: "kubernetes-docker",
    description: "Containerization and orchestration with Docker and Kubernetes. Learn to deploy scalable applications and manage clusters.",
    category: "Cloud",
    categorySlug: "cloud",
    level: "Intermediate",
    price: 60,
    duration: "4 months",
    instructor: "Ali Khan",
    rating: 4.7,
    popularity: 80,
    createdAt: "2026-02-01",
    image: "https://i.imgur.com/F8f8pYN.jpg",
  },
  {
    id: 17,
    title: "Cybersecurity Fundamentals",
    slug: "cybersecurity-fundamentals",
    description: "Learn the basics of cybersecurity, threats, encryption, network security, penetration testing, and securing systems.",
    category: "Security",
    categorySlug: "security",
    level: "Beginner",
    price: 50,
    duration: "3 months",
    instructor: "Hina Ali",
    rating: 4.5,
    popularity: 78,
    createdAt: "2026-01-30",
    image: "https://i.imgur.com/w5TzQGk.jpg",
  },
  {
    id: 18,
    title: "Python Automation",
    slug: "python-automation",
    description: "Automate tasks using Python: web scraping, file handling, Excel automation, email automation, and creating scripts to save time.",
    category: "Data Science",
    categorySlug: "data-science",
    level: "Intermediate",
    price: 45,
    duration: "3 months",
    instructor: "Ali Raza",
    rating: 4.6,
    popularity: 82,
    createdAt: "2026-02-02",
    image: "https://i.imgur.com/L8U9hRN.jpg",
  },
  {
    id: 19,
    title: "WordPress Development",
    slug: "wordpress-development",
    description: "Learn to build websites with WordPress: themes, plugins, custom post types, page builders, and deploying live sites.",
    category: "Web Development",
    categorySlug: "web-development",
    level: "Beginner",
    price: 25,
    duration: "2 months",
    instructor: "Sara Ahmed",
    rating: 4.4,
    popularity: 70,
    createdAt: "2026-01-28",
    image: "https://i.imgur.com/bCk9g1M.jpg",
  },
  {
    id: 20,
    title: "SEO & Digital Marketing",
    slug: "seo-digital-marketing",
    description: "Master SEO, content marketing, keyword research, link building, and analytics to improve website traffic and online presence.",
    category: "Marketing",
    categorySlug: "marketing",
    level: "Intermediate",
    price: 35,
    duration: "3 months",
    instructor: "Ali Raza",
    rating: 4.6,
    popularity: 77,
    createdAt: "2026-02-04",
    image: "https://i.imgur.com/0Tq5u8c.jpg",
  },
];
